language: node_js
node_js:
  - 12
os: linux
dist: bionic
install: true

env:
  - NODE_ENV=production DOCKER_CLI_EXPERIMENTAL=enabled TARGET_ARCHS=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6

stages:
  - test
  - name: deploy
    if: branch = master && type != pull_request

before_install:
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  
jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn ci-test
    - stage: deploy
      script:
        - make install
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx build --cache-from=anjsudh24/retro-board-maintenance:canary --pull --platform ${TARGET_ARCHS} -f ./retro-board-maintenance/Dockerfile -t anjsudh24/retro-board-maintenance:${PACKAGE_VERSION} -t anjsudh24/retro-board-maintenance:latest --push ./retro-board-maintenance
        - docker buildx build --cache-from=anjsudh24/retro-board-frontend:canary --pull --platform ${TARGET_ARCHS} -f ./retro-board-app/Dockerfile -t anjsudh24/retro-board-frontend:${PACKAGE_VERSION} -t anjsudh24/retro-board-frontend:latest --push .
        - docker buildx build --cache-from=anjsudh24/retro-board-backend:canary --pull --platform ${TARGET_ARCHS} -f ./retro-board-server/Dockerfile -t anjsudh24/retro-board-backend:${PACKAGE_VERSION} -t anjsudh24/retro-board-backend:latest --push .
    
